dataset:
  name: dsec
  data_dir: ${oc.env:PROJECT_ROOT, ..}/datasets/dsec-det
  split_config: ${oc.env:PROJECT_ROOT, ..}/data/dataset/dsec/detection/split.yaml
  orig_size: [480, 640]
  target_size: ???
  downsample_by_factor_2: false

  ev_representation: event_frame
  tau_ms: 50
  delta_t_ms: 50

  augmentation:
      prob_hflip: 0.5
      rotate:
        prob: 0.8
        min_angle_deg: -6
        max_angle_deg: 6
      zoom:
        prob: 0.8
        zoom_in:
          weight: 8
          factor:
            min: 1.0
            max: 1.5
        zoom_out:
          weight: 2
          factor:
            min: 1
            max: 1.2

  train:
    sequence_length: 1
    guarantee_labels: true
    
    
  val:
    sequence_length: 1
    guarantee_labels: false
    
   
  test:
    sequence_length: 1
    guarantee_labels: false
    