mode: gen1

input_dir: "/path/to/dataset/gen1/"
output_dir: "/path/to/dataset/gen1_pre/"
num_processors: 2

tau_ms: 50       # イベントを取得する間隔（ミリ秒）
delta_t_ms: 10   # 各取得におけるイベントの長さ（ミリ秒）

frame_shape: [240, 304]
downsample: false