mode: gen4

input_dir: /path/to/dataset/gen4/
output_dir: /path/to/dataset/pre_gen4_histogram/
num_processors: 2

representation_type: histogram # histogram or frame
bins: 10

tau_ms: 50       # イベントを取得する間隔（ミリ秒）
delta_t_ms: 50   # 各取得におけるイベントの長さ（ミリ秒）

frame_shape: [720, 1280]
downsample: true