input_dir: /path/to/dataset/DSEC/
output_dir: /path/to/dataset/dsec-det/
num_processors: 2

representation_type: frame # histogram or frame
bins: 10 

tau_ms: 50       # イベントを取得する間隔（ミリ秒）
delta_t_ms: 50   # 各取得におけるイベントの長さ（ミリ秒）

frame_shape: [480, 640]