input_dir: ${oc.env:DATA_DIR, /default/path}
output_dir: ${oc.env:DEST_DIR, /default/path}
num_processors: ${oc.env:NUM_PROCESS, 1}

representation_type: frame # histogram or frame
bins: 10 

tau_ms: 100       # イベントを取得する間隔（ミリ秒）
delta_t_ms: 50   # 各取得におけるイベントの長さ（ミリ秒）

frame_shape: [480, 640]