# config_list.yaml
model_configs:
  - ./config/model/yolox/yolox-s.yaml

exp_configs:
  - ./config/experiment/single/train.yaml

dataset_configs:
  - ./config/dataset/gen1/event_frame/single/tau=100_dt=10.yaml
  - ./config/dataset/gen1/event_frame/single/tau=100_dt=20.yaml
  - ./config/dataset/gen1/event_frame/single/tau=100_dt=33.yaml
  - ./config/dataset/gen1/event_frame/single/tau=100_dt=50.yaml
