# config_list.yaml
model_configs:
  - ${oc.env:PROJECT_ROOT}/config/model/rvt_detector/rvt_frame.yaml

exp_configs:
  - ${oc.env:PROJECT_ROOT}/config/experiment/sequence/train.yaml

dataset_configs:
  - ${oc.env:PROJECT_ROOT}/config/dataset/gen1/event_frame/sequence/base.yaml
  
parameters:
  param1:
    delta_t_ms: 5
    tau_ms: 100
  param2:
    delta_t_ms: 10
    tau_ms: 100
  param3:
    delta_t_ms: 20
    tau_ms: 100
  param4:
    delta_t_ms: 33
    tau_ms: 100
  param5:
    delta_t_ms: 50
    tau_ms: 100
  param6:
    delta_t_ms: 100
    tau_ms: 100
  