model:
  name: sast
  type: rnn
  
  backbone:
    name: SAST
    compile:
      enable: False
      args:
        mode: reduce-overhead
    input_channels: 3
    enable_masking: False
    partition_split_32: 1
    embed_dim: 32
    dim_multiplier: [1, 2, 4, 8]
    num_blocks: [1, 1, 1, 1]
    T_max_chrono_init: [4, 8, 16, 32]
    stem:
      patch_size: 4
    stage:
      downsample:
        type: patch
        overlap: True
        norm_affine: True
      attention:
        use_torch_mha: False
        partition_size: ???
        dim_head: 32
        attention_bias: True
        mlp_activation: gelu
        mlp_gated: False
        mlp_bias: True
        mlp_ratio: 4
        drop_mlp: 0
        drop_path: 0
        ls_init_value: 1e-5
        enable_CB: False
        AMP: 2e-4
        BOUNCE: 1e-3
      lstm:
        dws_conv: False
        dws_conv_only_hidden: True
        dws_conv_kernel_size: 3
        drop_cell_update: 0
    in_res_hw:
      - ???
      - ???
  
  
  neck:
    name: pafpn
    depth: 0.33
    in_stages: [2, 3, 4]
    in_channels: ???
    depthwise: false
    act: silu


  head:
    name: yolox
    num_classes: ???
    strides: ???
    in_channels: ???
    act: silu
    depthwise: false

  postprocess:
    conf_thre: 0.1
    nms_thre: 0.45
